services:
  #nginx:
    #build: 
      #context: .
      #dockerfile: nginx/Dockerfile
    #container_name: livedesk_nginx
    #ports:
     # - "80:80"
    #depends_on:
    #- backend
  
  backend1:
    build: ./backend
    container_name: livedesk_backend1
    ports:
      - "4001:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - INSTANCE_NAME=backend1
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    restart: always

  backend2:
    build: ./backend
    container_name: livedesk_backend2
    ports:
      - "4002:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - INSTANCE_NAME=backend2
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    restart: always

  backend3:
    build: ./backend
    container_name: livedesk_backend3
    ports:
      - "4003:4000"
    depends_on:
      - postgres
      - redis
    env_file:
      - ./backend/.env
    environment:
      - INSTANCE_NAME=backend3
      - DB_HOST=postgres
      - DB_PORT=5432
      - REDIS_HOST=redis
    restart: always
    
  postgres:
    image: postgres:15
    container_name: livedesk_postgres
    environment:
      POSTGRES_DB: livedesk
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: livedesk_redis

volumes:
  pgdata:
